# Generated by Django 3.2.12 on 2022-02-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeform', '0003_rename_name_form_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
