# Generated by Django 3.2.12 on 2022-03-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeform', '0005_auto_20220214_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='meta',
            field=models.JSONField(blank=True, help_text='Additional data for the field', null=True, verbose_name='Meta'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='kind',
            field=models.CharField(choices=[('TEXT', 'text'), ('DROPDOWN', 'dropdown'), ('RADIO', 'radio'), ('GENERIC', 'generic')], max_length=20),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='options',
            field=models.JSONField(blank=True, null=True, verbose_name='Dropdown Options'),
        ),
    ]
