# Generated by Django 3.2.12 on 2022-04-05 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typeform', '0006_auto_20220328_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='value',
        ),
    ]
